task: Add MLT jobs and update hardcoded values for cronjob-logs
DecisiveAI/mdai-inkops pull request #16
Opened 2024-03-21 16:54 UTC by o11yguru

### Any background context you want to provide for reviewers?
Add MLT jobs and update hardcoded values for cronjob-logs

2024-03-21 17:06 UTC, arcanez requested changes
how are `jobs/job-*.yaml` different from `jobs/cronjob-*.yaml`?

2024-03-21 17:06 UTC, arcanez commented on jobs/job-metrics.yaml
> +  name: demo-log-job
```suggestion
  name: demo-metric-job
```

2024-03-21 17:06 UTC, arcanez commented on jobs/job-traces.yaml
> +  name: demo-log-job
```suggestion
  name: demo-trace-job
```

2024-03-22 16:50 UTC, o11yguru commented
> how are `jobs/job-*.yaml` different from `jobs/cronjob-*.yaml`?

We may sometimes want to send data once and only once vs. continuously

2024-03-22 16:54 UTC, arcanez approved these changes

2024-06-03 15:40 UTC, merged